package ukma.speedyfix.domain.type;

public enum EngineType {
    PETROL_NATURALLY_ASPIRATED,
    PETROL_SUPERCHARGED,
    PETROL_TURBO,
    PETROL_NATURALLY_ASPIRATED_HYBRID,
    PETROL_SUPERCHARGED_HYBRID,
    PETROL_TURBO_HYBRID,
    DIESEL_NATURALLY_ASPIRATED,
    DIESEL_SUPERCHARGED,
    DIESEL_TURBO,
    DIESEL_NATURALLY_ASPIRATED_HYBRID,
    DIESEL_SUPERCHARGED_HYBRID,
    DIESEL_TURBO_HYBRID,
    ELECTRIC
}
